CREATE TABLE EVENTO (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DATA_INICIO DATE NOT NULL,
    DATA_FIM DATE NOT NULL,
    ATIVO BOOLEAN DEFAULT TRUE NOT NULL
) ENGINE = InnoDB;

CREATE TABLE EQUIPE (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    EVENTO_ID INT UNSIGNED NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    CONSTRAINT FK_EQUIPE_EVENTO FOREIGN KEY (EVENTO_ID) REFERENCES EVENTO (ID),
    CONSTRAINT UQ_EQUIPE_EVENTO_NOME UNIQUE (EVENTO_ID, NOME)
) ENGINE = InnoDB;

CREATE TABLE CATEGORIA (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    EVENTO_ID INT UNSIGNED NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    ORDEM INT NOT NULL,
    ATIVO BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT FK_CATEGORIA_EVENTO FOREIGN KEY (EVENTO_ID) REFERENCES EVENTO (ID),
    CONSTRAINT UQ_CATEGORIA_EVENTO_NOME UNIQUE (EVENTO_ID, NOME)
) ENGINE = InnoDB;

CREATE TABLE CRITERIO (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CATEGORIA_ID INT UNSIGNED NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    ORDEM INT NOT NULL,
    ATIVO BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT FK_CRITERIO_CATEGORIA FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA (ID),
    CONSTRAINT UQ_CRITERIO_CATEGORIA_NOME UNIQUE (CATEGORIA_ID, NOME)
) ENGINE = InnoDB;

CREATE TABLE JURADO (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    EVENTO_ID INT UNSIGNED NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    ATIVO BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT FK_JURADO_EVENTO FOREIGN KEY (EVENTO_ID) REFERENCES EVENTO (ID),
    CONSTRAINT UQ_JURADO_EVENTO_NOME UNIQUE (EVENTO_ID, NOME)
) ENGINE = InnoDB;

CREATE TABLE JURADO_CATEGORIA (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    JURADO_ID INT UNSIGNED NOT NULL,
    CATEGORIA_ID INT UNSIGNED NOT NULL,
    CONSTRAINT FK_JURADO_CATEGORIA_JURADO FOREIGN KEY (JURADO_ID) REFERENCES JURADO (ID),
    CONSTRAINT FK_JURADO_CATEGORIA_CATEGORIA FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA (ID),
    CONSTRAINT UQ_JURADO_CATEGORIA UNIQUE (JURADO_ID, CATEGORIA_ID)
) ENGINE = InnoDB;

CREATE TABLE AVALIACAO (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    EQUIPE_ID INT UNSIGNED NOT NULL,
    CATEGORIA_ID INT UNSIGNED NOT NULL,
    JURADO_ID INT UNSIGNED NOT NULL,
    CONSTRAINT FK_AVALIACAO_EQUIPE FOREIGN KEY (EQUIPE_ID) REFERENCES EQUIPE (ID),
    CONSTRAINT FK_AVALIACAO_CATEGORIA FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA (ID),
    CONSTRAINT FK_AVALIACAO_JURADO FOREIGN KEY (JURADO_ID) REFERENCES JURADO (ID),
    CONSTRAINT UQ_AVALIACAO UNIQUE (
        EQUIPE_ID,
        CATEGORIA_ID,
        JURADO_ID
    )
) ENGINE = InnoDB;

CREATE TABLE NOTA (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    AVALIACAO_ID INT UNSIGNED NOT NULL,
    CRITERIO_ID INT UNSIGNED NOT NULL,
    NOTA INT NOT NULL,
    CONSTRAINT FK_NOTA_AVALIACAO FOREIGN KEY (AVALIACAO_ID) REFERENCES AVALIACAO (ID),
    CONSTRAINT FK_NOTA_CRITERIO FOREIGN KEY (CRITERIO_ID) REFERENCES CRITERIO (ID),
    CONSTRAINT CK_NOTA_VALOR CHECK (
        NOTA >= 0
        AND NOTA <= 100
    ),
    CONSTRAINT UQ_NOTA_AVALIACAO_CRITERIO UNIQUE (AVALIACAO_ID, CRITERIO_ID)
) ENGINE = InnoDB;

CREATE TABLE MOVIMENTACAO_PONTUACAO (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    EVENTO_ID INT UNSIGNED NOT NULL,
    EQUIPE_ID INT UNSIGNED NOT NULL,
    TIPO VARCHAR(20) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    PONTOS INT NOT NULL,
    DATA_LANCAMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_MOV_PONTUACAO_EVENTO FOREIGN KEY (EVENTO_ID) REFERENCES EVENTO (ID),
    CONSTRAINT FK_MOV_PONTUACAO_EQUIPE FOREIGN KEY (EQUIPE_ID) REFERENCES EQUIPE (ID),
    CONSTRAINT CK_MOV_PONTUACAO_TIPO CHECK (
        TIPO IN (
            'BONUS',
            'PENALIDADE',
            'PONTUACAO'
        )
    ),
    CONSTRAINT CK_MOV_PONTUACAO_VALOR CHECK (PONTOS <> 0)
) ENGINE = InnoDB;