CREATE TABLE USUARIO (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    DATA_CRIACAO TIMESTAMP DEFAULT(CURRENT_TIME),
    NOME VARCHAR(100) UNIQUE NOT NULL,
    SENHA_HASH VARCHAR(100) NOT NULL
);

ALTER TABLE jurado AUTO_INCREMENT = 1000;

ALTER TABLE JURADO ADD LOGIN VARCHAR(100) NOT NULL;

ALTER TABLE JURADO ADD CONSTRAINT UQ_JURADO_LOGIN UNIQUE (LOGIN);